// Generated by iosApp/generate_string_catalog.py — do not edit by hand.
import Foundation

/// Localized Android `strings.xml` lookup by resource name.
enum L {
    private static var lang: AppLanguage { AppLocalization.language }

    static func t(_ key: String) -> String {
        AndroidStrings.text(key, language: lang)
    }

    static func tf(_ key: String, _ args: CVarArg...) -> String {
        var template = t(key)
        guard !args.isEmpty else { return template }
        // Android `%d`/`%s` are normalized to `%@`; avoid String(format:) with raw integers.
        template = template.replacingOccurrences(of: "%%", with: "\u{0001}")
        for arg in args {
            guard let range = template.range(of: "%@") else { break }
            template.replaceSubrange(range, with: stringValue(for: arg))
        }
        return template.replacingOccurrences(of: "\u{0001}", with: "%")
    }

    private static func stringValue(for value: CVarArg) -> String {
        if let string = value as? String { return string }
        if let number = value as? NSNumber { return number.stringValue }
        switch value {
        case let int as Int: return String(int)
        case let int32 as Int32: return String(int32)
        case let int64 as Int64: return String(int64)
        case let uint as UInt: return String(uint)
        case let double as Double: return String(double)
        case let float as Float: return String(float)
        default:
            return String(describing: value)
        }
    }
}
