// Generated by iosApp/generate_string_catalog.py — do not edit by hand.
import Foundation

/// Localized Android `strings.xml` lookup by resource name.
enum L {
    private static var lang: AppLanguage { AppLocalization.language }

    static func t(_ key: String) -> String {
        AndroidStrings.text(key, language: lang)
    }

    static func tf(_ key: String, _ args: CVarArg...) -> String {
        let template = t(key)
        guard !args.isEmpty else { return template }
        return String(format: template, locale: Locale.current, arguments: args)
    }
}
