import Foundation

/// German UI strings aligned with Android `values/strings.xml`.
enum S {
    static let appName = "2-Stroke Calc"
    static let splashSlogan = "sonst brauchst Du nichts…"
    static let navCalculator = "Rechner"
    static let navVehicles = "Fahrzeuge"
    static let settingsTitle = "Einstellungen"
    static let adminPanelTitle = "Admin"
    static let calculatorOverviewSubtitle = "Wähle einen Rechner für deine 2-Takt-Berechnung."
    static let calculatorBack = "Zurück zur Übersicht"
    static let loginTitle = "Anmelden"
    static let loginSubtitle = "Melde dich an, um Fahrzeuge und Cloud-Sync zu nutzen."
    static let emailLabel = "E-Mail"
    static let passwordLabel = "Passwort"
    static let loginButton = "Anmelden"
    static let forgotPassword = "Passwort vergessen?"
    static let signInGoogle = "Mit Google anmelden"
    static let noAccountRegister = "Noch kein Konto? Registrieren"
    static let registerTitle = "Registrieren"
    static let registerButton = "Konto erstellen"
    static let displayNameLabel = "Anzeigename"
    static let forgotPasswordTitle = "Passwort zurücksetzen"
    static let forgotPasswordButton = "Link senden"
    static let accountTitle = "Konto"
    static let logout = "Abmelden"
    static let proReadOnly = "Pro-Modul – nur Lesen. Upgrade für volle Bearbeitung."
    static let buyPro = "Pro kaufen"
    static let welcomeTitle = "Willkommen bei 2-Stroke Calc"
    static let welcomeContinue = "Weiter"
    static let permissionsTitle = "Berechtigungen"
    static let permissionsContinue = "Fortfahren"
    static let vehiclesEmpty = "Noch keine Fahrzeuge"
    static let vehiclesAdd = "Fahrzeug hinzufügen"
    static let save = "Speichern"
    static let cancel = "Abbrechen"
    static let delete = "Löschen"
    static let calculate = "Berechnen"
    static let resultTitle = "Ergebnis"
    static let sectionInput = "Dateneingabe"
    static let proUpsellTitle = "Pro-Feature"
    static let authGateTitle = "Anmeldung erforderlich"
    static let authGateMessage = "Bitte melde dich an, um fortzufahren."
    static let authGateLogin = "Zum Login"

    // Settings
    static let settingsAccountSection = "Konto"
    static let settingsAccountSubtitle = "Anmeldung, Profil, Pro-Version und Sicherheit"
    static let settingsProSection = "Pro-Version"
    static let settingsProSectionHint = "Schalte Fahrzeuge, Steuerzeiten, Kabelquerschnitt, Flüssigkeitsrechner und Getrieberechner frei."
    static let settingsBuyPro = "Pro-Version kaufen"
    static let settingsRestorePro = "Käufe wiederherstellen"
    static let appearanceSection = "Darstellung"
    static let themeLabel = "Design"
    static let languageLabel = "Sprache"
    static let menuTypeLabel = "Menütyp"
    static let settingsPermissionsSection = "Berechtigungen"
    static let settingsNotificationsTitle = "Push-Benachrichtigungen"
    static let settingsNotificationsGranted = "Aktiv – Wartungserinnerungen für Fahrzeuge"
    static let settingsNotificationsDenied = "Deaktiviert – keine Wartungserinnerungen"
    static let settingsGeneralSection = "Allgemein"
    static let settingsHelpTitle = "Hilfe & FAQ"
    static let settingsHelpSubtitle = "Rechner, Fahrzeuge, Pro-Version und mehr"
    static let settingsHelpBody = "Kurze Antworten und praktische Tipps zur Nutzung von 2-Stroke Calc.\n\n• Alle Rechner unter dem Tab Rechner.\n• Fahrzeuge mit Cloud-Sync bei angemeldetem Konto.\n• Pro schaltet Bearbeiten in gesperrten Modulen frei.\n• Design, Sprache und Menütyp unter Darstellung."
    static let settingsChangelogTitle = "Versionshistorie"
    static let settingsChangelogSubtitle = "Neuigkeiten in Version 1.2.6"
    static let settingsChangelogBody = "Version 1.0 iOS: SwiftUI-App, 16 Rechner, Firebase-Auth, StoreKit, Fahrzeuge/Firestore, Walkthrough."
    static let settingsContactTitle = "Kontakt"
    static let settingsContactSubtitle = "Nachricht senden oder Fehler melden"
    static let settingsContactBody = "Schreib uns gern direkt aus der App – ob Frage, Feedback oder Fehlerbericht."
    static let settingsBugReportTitle = "Fehler melden"
    static let settingsBugReportSubtitle = "Problem mit der App beschreiben"
    static let settingsBugReportBody = "Beschreibe das Problem so genau wie möglich. Geräteinformationen werden automatisch angehängt."
    static let settingsLegalSection = "Rechtliches"
    static let settingsPrivacyTitle = "Datenschutz"
    static let settingsPrivacyBody = "Rechner-Eingaben werden lokal verarbeitet. Fahrzeugdaten synchronisieren über Firebase. Pro-Käufe über App Store."
    static let settingsTermsTitle = "AGB"
    static let settingsTermsBody = "Die App dient als Hilfsmittel für technische Berechnungen. Ergebnisse ersetzen keine fachliche Prüfung. Pro-Käufe unterliegen App-Store-Richtlinien."
    static let settingsDataProcessingTitle = "Datenverarbeitung"
    static let settingsImprintTitle = "Impressum"
    static let settingsRestartWalkthrough = "App-Tour erneut starten"

    // Walkthrough
    static let walkthroughFreeWelcomeTitle = "Willkommen bei 2-Stroke Calc!"
    static let walkthroughFreeWelcomeBody = "In der kostenlosen Version kannst du alle Rechner und Fahrzeuge ansehen. Bearbeiten schaltest du mit Pro frei."
    static let walkthroughProWelcomeTitle = "Willkommen bei 2-Stroke Calc Pro!"
    static let walkthroughProWelcomeBody = "Du hast die Pro-Version – wir zeigen dir kurz Rechner, Fahrzeuge und Einstellungen."
    static let walkthroughCalculatorNavTitle = "Rechner"
    static let walkthroughFreeCalculatorNavBody = "Hier findest du alle 2-Takt-Rechner. Das PRO-Badge markiert Rechner, deren Eingaben Pro erfordern."
    static let walkthroughProCalculatorNavBody = "Hier findest du alle 2-Takt-Rechner – inklusive Steuerzeiten, Kabelquerschnitt und Getriebe."
    static let walkthroughFreeCalculatorTitle = "Voll nutzbare Rechner"
    static let walkthroughFreeCalculatorBody = "Diese Rechner kannst du vollständig nutzen – öffnen, Werte eingeben und Ergebnisse berechnen."
    static let walkthroughLockedCalculatorTitle = "Rechner mit PRO-Badge"
    static let walkthroughLockedCalculatorBody = "Diese Rechner kannst du ansehen. Eingaben ändern ist Teil der Pro-Version."
    static let walkthroughProCalculatorListTitle = "Rechner auswählen"
    static let walkthroughProCalculatorListBody = "Tippe auf einen Rechner, um Berechnungen durchzuführen."
    static let walkthroughFreeVehiclesNavTitle = "Fahrzeuge"
    static let walkthroughFreeVehiclesNavBody = "Demo-Fahrzeuge ansehen ist kostenlos – bearbeiten, hinzufügen und löschen erfordert Pro."
    static let walkthroughVehiclesNavTitle = "Fahrzeuge"
    static let walkthroughProVehiclesNavBody = "Verwalte deinen Fuhrpark – Stammdaten, Wartung, Tuning und Verbrauch dokumentieren."
    static let walkthroughVehiclesAddTitle = "Fahrzeug anlegen"
    static let walkthroughProVehiclesAddBody = "Mit dem Plus-Button legst du ein neues Moped, Mokick oder einen Roller an."
    static let walkthroughSettingsNavTitle = "Einstellungen"
    static let walkthroughFreeSettingsNavBody = "Design, Sprache, Konto und der Bereich Pro-Version findest du hier."
    static let walkthroughProSettingsNavBody = "Design, Sprache, Konto und weitere App-Optionen findest du hier."
    static let walkthroughSettingsProTitle = "Pro-Version kaufen"
    static let walkthroughSettingsProBody = "Hier kaufst oder stellst du die Pro-Version wieder her – für Bearbeiten in Rechnern und Fahrzeugen."
    static let walkthroughSettingsAppearanceTitle = "Darstellung anpassen"
    static let walkthroughSettingsAppearanceBody = "Wähle helles oder dunkles Design, Sprache und Menütyp nach deinem Geschmack."
    static let walkthroughStepCounter = "Schritt %d von %d"
    static let walkthroughSkip = "Überspringen"
    static let walkthroughBack = "Zurück"
    static let walkthroughNext = "Weiter"
    static let walkthroughFinish = "Fertig"

    static func calculatorTab(_ id: CalculatorId) -> String {
        switch id {
        case .timing: return "Steuerzeiten"
        case .portArea: return "Time-Area"
        case .ignition: return "Zündzeitpunkt"
        case .dcCable: return "Kabelquerschnitt"
        case .fluid: return "Flüssigkeitsrechner"
        case .compression: return "Verdichtung"
        case .squishBand: return "Quetschfläche"
        case .meanPressure: return "Mitteldruck"
        case .gear: return "Getriebe"
        case .exhaust: return "Resorohr"
        case .counterweight: return "Wuchtfaktor"
        case .variatorWeight: return "Variogewichte"
        case .fuelMix: return "Öl/Benzin"
        case .carbJet: return "Vergaserdüse"
        case .dynoInertia: return "Schwungmasse"
        case .vehicleDynamics: return "Fahrdynamik"
        default: return id.name
        }
    }

    static func calculatorDescription(_ id: CalculatorId) -> String {
        switch id {
        case .timing: return "Steuerzeiten, Überströmgrad und Diagramm aus Stichmaßen."
        case .portArea: return "Transfer-Querschnitt, Time-Area und Auslassgeometrie mit Kennzahlen."
        case .ignition: return "Zündzeitpunkt vor OT in Grad und Millimeter umrechnen."
        case .dcCable: return "DC-Kabelquerschnitt aus Strom, Leitungslänge und zulässigem Spannungsfall."
        case .fluid: return "Flüssigkeitsmischungen für Werkstatt und Galvanik."
        case .compression: return "Verdichtungsverhältnis, Brennraum und Quetschfläche berechnen."
        case .squishBand: return "Quetschfläche und Quetschkantenbreite aus Bohrung und Glocke."
        case .meanPressure: return "Mitteldruck, Drehmoment und Literleistung aus Leistungsdaten."
        case .gear: return "Geschwindigkeiten, Schaltpunkte und Drehzahlsprung aus Getriebeübersetzungen."
        case .exhaust: return "Resorohr nach Blair berechnen – Diffusor-Segmente mit Vorschau."
        case .counterweight: return "Wuchtfaktor aus Kolben-, Pleuel- und Meistergewicht."
        case .variatorWeight: return "Variogewichte für Roller/Mofa schätzen."
        case .fuelMix: return "Öl- und Benzinmenge für das Mischverhältnis berechnen."
        case .carbJet: return "Hauptdüse für Höhe und Temperatur anpassen."
        case .dynoInertia: return "Trägheitsmoment und äquivalente Masse für Prüfstandswalzen."
        case .vehicleDynamics: return "Beschleunigung, Zugkraft und Höchstgeschwindigkeit berechnen."
        default: return ""
        }
    }
}
